import axios from 'axios';

export function get({
  url,
  transformRequest,
  transformResponse,
  headers,
  params,
  paramsSerializer,
  timeout,
  withCredentials,
  adapter,
  auth,
  responseType,
  responseEncoding,
  xsrfCookieName,
  xsrfHeaderName,
  onUploadProgress,
  onDownloadProgress,
  maxContentLength,
  maxBodyLength,
  validateStatus,
  maxRedirects,
  socketPath,
  httpAgent,
  httpsAgent,
  proxy,
  cancelToken,
  decompress,
}) {
  return axios
    .request({
      url,
      method: 'GET',
      transformRequest,
      transformResponse,
      headers,
      params,
      paramsSerializer,
      timeout,
      withCredentials,
      adapter,
      auth,
      responseType,
      responseEncoding,
      xsrfCookieName,
      xsrfHeaderName,
      onUploadProgress,
      onDownloadProgress,
      maxContentLength,
      maxBodyLength,
      validateStatus,
      maxRedirects,
      socketPath,
      httpAgent,
      httpsAgent,
      proxy,
      cancelToken,
      decompress,
    })
    .then(result => result)
    .catch(error => error);
}
